### ISSUE TITLE
Build Error: Unable to resolve project target 'Google Inc.:GoogleAPIs:19'

### ISSUE THREAD

**Issue by alastairparagas** [ludei/cocoonjs-cli#9]
When I try to run my project, this error comes up:

```
[CocoonJS] Generating config.xml from defaults for platform "android"
[CocoonJS] Calling plugman.prepare for platform "android"
Preparing android project
Processing configuration changes for plugins.
Iterating over installed plugins: [ 'com.ionic.keyboard',
  'org.apache.cordova.console',
  'org.apache.cordova.device',
  'org.apache.cordova.file-transfer',
  'org.apache.cordova.camera',
  'org.apache.cordova.dialogs',
  'nl.x-services.plugins.toast',
  'org.apache.cordova.network-information',
  'com.ludei.webview.plus',
  'org.apache.cordova.file' ]
Writing out cordova_plugins.js...
Wrote out Android application name to "R8M3"
no icon found matching Android typical densities
no icon found matching Android typical densities
no icon found matching Android typical densities
no icon found matching Android typical densities
Wrote out Android package name to "com.stela.rateMe"
Running command: C:\xampp\htdocs\R8M3-App\platforms\android\cordova\run.bat
[CocoonJS] Unable to locate tools.jar. Expected to find it in C:\Program Files\Java\jre6\lib\tools.jar
[CocoonJS]
[CocoonJS] Buildfile: C:\xampp\htdocs\R8M3-App\platforms\android\build.xml
[CocoonJS]
-set-mode-check:
[CocoonJS]
-set-debug-files:
[CocoonJS]
[CocoonJS]
-check-env:
[CocoonJS]  [checkenv] Android SDK Tools Revision 22.6.4
[CocoonJS]  [checkenv] Installed at C:\Android\sdk

-setup:
[CocoonJS]      [echo] Project Name: HelloCordova
[CocoonJS]   [gettype] Project Type: Application
[CocoonJS]
-set-debug-mode:
[CocoonJS]
-debug-obfuscation-check:
[CocoonJS]

-pre-build:
[CocoonJS]
-build-setup:
[CocoonJS] [getbuildtools] Using latest Build Tools: 19.1.0
[CocoonJS]      [echo] Resolving Build Target for HelloCordova...
[CocoonJS] [gettarget] Project Target:   Android 4.4.2
[CocoonJS] [gettarget] API level:        19
[CocoonJS]      [echo] ----------
[CocoonJS]      [echo] Creating output directories if needed...
[CocoonJS]
[CocoonJS]      [echo] ----------
[CocoonJS]
[CocoonJS]      [echo] Resolving Dependencies for HelloCordova...
[CocoonJS] [dependency] Library dependencies:
[CocoonJS] [dependency]
[dependency] ------------------
[dependency] Ordered libraries:
[CocoonJS] [dependency]
[CocoonJS] [dependency] ------------------
[CocoonJS]      [echo] ----------
[CocoonJS]      [echo] Building Libraries with 'debug'...
[CocoonJS]
[CocoonJS]
nodeps:
[CocoonJS]
-set-mode-check:

-set-debug-files:
[CocoonJS]
-check-env:
[CocoonJS]
[CocoonJS]  [checkenv] Android SDK Tools Revision 22.6.4
[CocoonJS]  [checkenv] Installed at C:\Android\sdk

-setup:
[CocoonJS]      [echo] Project Name: LudeiChromium
[CocoonJS]   [gettype] Project Type: Android Library
[CocoonJS]
[CocoonJS]
-set-debug-mode:
[CocoonJS]
-debug-obfuscation-check:
[CocoonJS]
-pre-build:

-build-setup:
[CocoonJS] [getbuildtools] Using latest Build Tools: 19.1.0
[CocoonJS]      [echo] Resolving Build Target for LudeiChromium...

BUILD FAILED
C:\Android\sdk\tools\ant\build.xml:601: The following error occurred while executing this line:
C:\Android\sdk\tools\ant\build.xml:542: Unable to resolve project target 'Google Inc.:Google APIs:19'

Total time: 2 seconds


C:\xampp\htdocs\R8M3-App\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s,/c,ant,debug,-f,C:\xampp\htdocs\R8M3-App\platforms\android\build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen

[CocoonJS] Command finished with error code 8: C:\xampp\htdocs\R8M3-App\platforms\android\cordova\run.bat
Error: C:\xampp\htdocs\R8M3-App\platforms\android\cordova\run.bat: Command failed with exit code 8
    at ChildProcess.whenDone (C:\Users\aparagas\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:131:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)


C:\xampp\htdocs\R8M3-App>
```

Before trying to run/build the project, I had an error on adding the Webview+ plugin, but I was able to resolve it by injecting this property to my project.properties file `android.library.reference.1=..\\..\\..\\plugins\\com.ludei.webview.plus\\android` and running the -d flag. 

I have Android API 19, currently implementing this on an Ionic Framework project. I would love to implement Webview+ to provide consistent performance across the future user-base of the app I am building, but cannot get it to run with this error at hand.

**Comment by IsmaBit** [comment]
Hi @alastairparagas, i've the same problem but with ionic.
I resolve that verify where the folder apache ant were place. In 64bit system the folder "Programs File(x86)" needs administrator permission.
My ant folder were place there, so when i try to build my project will block beacuse can not have the permission to get information in the folder. I change the place of the folder from "Programs File(x86)" to "Programs File". Maybe some files that you use it's protected.

**Comment by alastairparagas** [comment]
@IsmaBit Ionic now supports simple Crosswalk integration using the command line (with their latest CLI version), so I've somewhat stepped out of cocoonjs. Will see if I see anything to note.

**Comment by umcsdon** [comment]
@ludei Any updates on this problem?
